### ISSUE TITLE
Cannot start snap installation

### ISSUE THREAD

**Issue by darealshinji** [notepadqq/notepadqq#1068]
**Describe the bug**
I've installed nqq through snap but it doesn launch.

**To Reproduce**
```sh
 $ sudo snap install core22
core22 20220902 aus Canonical✓ installiert
 $ notepadqq 
/snap/notepadqq/855/usr/local/lib/notepadqq/notepadqq-bin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /var/lib/snapd/lib/gl/libGLdispatch.so.0)
/snap/notepadqq/855/usr/local/lib/notepadqq/notepadqq-bin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /var/lib/snapd/lib/gl/libGLX.so.0)
```

**Expected behavior**
Program should launch

**Screenshots**

**Environment (please complete the following information):**
 - Ubuntu 22.04
 - Installation type: snap
 - Qt version: ??
 - Notepadqq version: ??

**Additional context**
Installing snap package core22 doesn't help.

**Comment by danieleds** [comment]
Thanks. We need to review the snap package - it was built quite a lot of time ago and it had a few issues which may have been fixed with the newest versions of Snap.

**Comment by Lorthiz** [comment]
@danieleds Hello, any update to this issue?

**Comment by darealshinji** [comment]
Built a snap from the current git version and it still doesn't run. And building a snap from core20 doesn't even work at all for me.
However you can easily build an AppImage:

``` bash
#!/bin/bash
# run this in Ubuntu 20.04 (schroot)
set -e
set -x

JOBS=6

sudo apt update
sudo apt upgrade
sudo apt install build-essential pkg-config git wget fuse qtbase5-dev qttools5-dev qtwebengine5-dev libqt5websockets5-dev libqt5svg5-dev libuchardet-dev

git clone "https://github.com/notepadqq/notepadqq" notepadqq-git
cd notepadqq-git

# build
./configure --prefix="$PWD/appdir/usr"
make -j$JOBS

# install
make install
rm -rf appdir/usr/bin/notepadqq appdir/usr/lib/notepadqq appdir/usr/share/notepadqq
cp -r out/release appdir/usr
cp out/release/lib/notepadqq-bin appdir/usr/bin/notepadqq

# deploy
wget -q -c -O deploy.AppImage "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
chmod a+x deploy.AppImage
./deploy.AppImage appdir/usr/share/applications/notepadqq.desktop -verbose=2 -bundle-non-qt-libs

# package
ln -fs ../release/bin/notepadqq appdir/usr/bin/notepadqq
wget -q -c "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
chmod a+x appimagetool-x86_64.AppImage
VERSION="$(git describe)" ./appimagetool-x86_64.AppImage appdir
```
