### ISSUE TITLE
Tab drag visual error

### ISSUE THREAD

**Issue by severach** [notepadqq/notepadqq#424]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

Open notepadqq with 2 or more tabs. I have 4 tabs.
Select the first tab.
Drag the first tab halfway towards the second. Stop. Do not release mouse.
Press ESC to cancel the drag.
Press F1 for help
Release mouse
Dismiss help window with mouse.

**Current behavior**
The tab sits in limbo half way towards the second tab.

**Expected behavior**
The tab snaps to a position with ESC, F1, or mouse release.

Click on the wayward tab to snap into position.

````
% pacman -Q linux qt5-base notepadqq-git 
linux 4.10.11-1
qt5-base 5.8.0-7
notepadqq-git 1.0.1.r34.g7a4e887-1
````

**Comment by Teklad** [comment]
So... I'm pretty sure this is fixed in the webengine-beta branch... if you dare to try.

**Comment by danieleds** [comment]
It's still an issue even in webengine-beta. It's probably a bug in the Qt widget itself.
