### ISSUE TITLE
Accents in Portuguese

### ISSUE THREAD

**Issue by leandrosob** [notepadqq/notepadqq#660]
**I'm submitting a ...**
[x] bug report 

**Current behavior**
Notepadqq is not accepting accents in Portuguese.

**Expected behavior**
Accent characters requiring more than one key pressed to generate the character are not generated, such as - ã é ó ê... among others.

**Minimal reproduction of the problem with instructions**
I'm using the US international keyboard layout. 
Press CTRL + 'a' to generate the character 'ã'. 
Press CTRL + 6 plus "e" to generate the character - ê.
Press' plus' and 'to generate the character - é.

**Please tell us about your environment:**
Ubuntu 18.04, Qt version 5.5.1, Notepadqq version v1.4.2

**Comment by danieleds** [comment]
This is probably fixed in the webengine2-promise branch.

If you want, you can give it a try by compiling from source.

**Comment by TheRauven** [comment]
This issue is still not solved, and for anyone using Notepadqq to write anything with accents, this makes it unusable.

Tested on Qt 5.5.1 with chars à, á, â, ã, è, é, ò, ó, ô, õ, there are probably more.
