### ISSUE TITLE
Notepadqq 1.4.2 thinks my settings specify tabs when I have "Use spaces instead of tabs"

### ISSUE THREAD

**Issue by aaronfranke** [notepadqq/notepadqq#684]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

Notepadqq warns me about tabs vs spaces when I have spaces in file and spaces in settings

**Expected behavior**

Notepadqq should not warn me about tabs vs spaces when I only specify spaces

**Minimal reproduction of the problem with instructions**

1. Have a file indented with spaces
2. Have settings set to use spaces (the language I'm using does not have overrides)
3. Notepadqq thinks I have it set to using tabs and gives me a warning when I open the file

![1](https://user-images.githubusercontent.com/1646875/40137781-d6a22770-5910-11e8-8618-700c36e23870.png)
![2](https://user-images.githubusercontent.com/1646875/40137787-d90495de-5910-11e8-9370-36cdfd6a3c4c.png)

**Please tell us about your environment:** Notepadqq v1.4.2 with Qt 5.9.5 from Xubuntu 18.04 repos.

**Comment by danieleds** [comment]
Thank you for your report, it was a regression introduced in a recent refactoring we did in ce1d67a1dbebad850cce23751ff4951b7e9d9156

**Comment by darealshinji** [comment]
Now that this issue was fixed, can you update the snap package on the edge channel?

**Comment by easyw** [comment]
Hi 
I have installed Notepadqq on Mint 19.1 with:
`sudo add-apt-repository ppa:notepadqq-team/notepadqq`
`sudo apt-get update`
`sudo apt-get install notepadqq`
and I still get 1.4.2 version with this bug.
`notepadqq --version`
`qt5ct: using qt5ct plugin`
`Notepadqq 1.4.2`

Is there a way to update to latest fixed release?
Thx

**Comment by easyw** [comment]
I'm just referencing here what I found:
https://github.com/notepadqq/notepadqq/issues/755#issuecomment-419135389

> I think this is the same issue as #684 which has been **fixed after the 1.4.8 release**.
> We're currently somewhat stuck fixing a few fundamental issues with some of our tech, that's why we haven't released a new version in a while. If you want to get your hands dirty **you can compile the current master branch to get the fix**; otherwise you'll probably have to wait until we sorted everything out. Sorry 'bout that.

**Comment by JuBan1** [comment]
You could either built it from source ([guide](https://github.com/notepadqq/notepadqq#build-it-yourself)) or use the Snap variant. I think Mint should have a software center app that has Snap software? I'm not very well versed with Mint.

**Comment by mnh48** [comment]
This issue came up as the first result in Google search so I'm dropping this here in case others came across it as well

If anyone else is stuck with...

1. Notepadqq 1.4.2 because that's the last version of Notepadqq available on APT and they dropped it to move to snap, OR
2. Notepadqq 1.4.8 because there seemed to not be any newer version available for Ubuntu 18.04.5 LTS i686 on Snap as of 17 September 2020, ...

... and you're annoyed with this bug which affected both 1.4.2 and 1.4.8, you can try this fix:

1. open the config file `Notepadqq.ini`
    - if you install with Snap, it should be at `~/snap/notepadqq/844/.config/Notepadqq/`
    - if you install with APT, it should be at `~/.config/Notepadqq/`
2. go to the `[Languages]` part
3. add these two in new lines (change the second line to 2 if you prefer 2 spaces instead of 4)
    ```ini
    default\IndentWithSpaces=true
    default\TabSize=4
    ```
4. save the file

From now on Notepadqq should be using spaces instead of tabs as the default when launched, plus modifying it this way wouldn't touch existing setting on the other languages if you had any of them customized as it only change the default value.

**Comment by voryzen** [comment]
@mnh48 so thankful that I found your post. Absolute lifesaver

**Comment by jens-st** [comment]
@mnh48 Thank you for the hint.

It's `~/.var/app/com.notepadqq.Notepadqq/config/Notepadqq/Notepadqq.ini` if you use flatpak.

**Comment by beauweta** [comment]
Still in s ~/.var/app/com.notepadqq.Notepadqq/config/Notepadqq/Notepadqq.ini if you use Linux Mint 21.3 Cinnamon.
So this bug is 5 years old? Really?
