### ISSUE TITLE
Make error compiling topeditorcontainer.cpp

### ISSUE THREAD

**Issue by elosantos** [notepadqq/notepadqq#717]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Make gives the following error compiling topeditorcontainer.cpp:

**topeditorcontainer.cpp:250:6:   required from here
topeditorcontainer.cpp:219:53: error: cannot call member function ‘EditorTabWidget* TopEditorContainer::tabWidget(int)’ without object
                             iteration(i-1, tabWidget(i-1)->count() - 1);
topeditorcontainer.cpp:224:54: error: cannot call member function ‘EditorTabWidget* TopEditorContainer::tabWidget(int)’ without object
                     EditorTabWidget *tabW = tabWidget(i);
topeditorcontainer.cpp:225:29: error: no match for call to ‘(const std::function<void(int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>, std::function<void()>)>) (const int&, const int&, EditorTabWidget*&, EditorNS::Editor*, std::function<void()>, TopEditorContainer::forEachEditorAsync(bool, std::function<void(int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>, std::function<void()>)>)::<lambda(const auto:1&, const auto:2&)>::<lambda(int, int)>::<lambda()> [with auto:1 = QtPromise::QPromiseResolve<void>; auto:2 = QtPromise::QPromiseReject<void>]::<lambda()>)’
                     callback(i, j, tabW, tabW->editor(j), iteration(i, j-1), [resolve](){ resolve(); });**

**Expected behavior**
No error
**Minimal reproduction of the problem with instructions**

This is the complete log of the configure and make commands:

root@HP-Debian:/home/emilio/notepadqq# ./configure --prefix /usr
checking for QT5 qmake... /usr/bin/qtchooser -run-tool=qmake -qt=5
checking for lrelease... /usr/bin/qtchooser -run-tool=lrelease -qt=5
checking for c++... /usr/bin/c++
checking whether c++ compiler builds test program... ok
checking whether c++ compiler supports -std=c++0x... ok
checking whether compiled test program works... ok
checking for make... /usr/bin/make
checking for pkg-config... /usr/bin/pkg-config
checking for Qt5Core library... -lQt5Core
checking for Qt5Gui library... -lQt5Gui -lQt5Core
checking for Qt5Network library... -lQt5Network -lQt5Core
checking for Qt5WebEngine library... -lQt5WebEngine -lQt5WebEngineCore -lQt5Quick -lQt5Gui -lQt5WebChannel -lQt5Qml -lQt5Network -lQt5Core
checking for Qt5Widgets library... -lQt5Widgets -lQt5Gui -lQt5Core
checking for Qt5WebEngineWidgets library... -lQt5WebEngineWidgets -lQt5WebEngineCore -lQt5WebChannel -lQt5Widgets -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core
checking for Qt5PrintSupport library... -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Core
checking for Qt5Svg library... -lQt5Svg -lQt5Widgets -lQt5Gui -lQt5Core
checking for Qt5WebSockets library... -lQt5WebSockets -lQt5Network -lQt5Core
checking for Qt5WebChannel library... -lQt5WebChannel -lQt5Qml -lQt5Network -lQt5Core
generate Makefile... Info: creating stash file /home/emilio/notepadqq/.qmake.stash
done
root@HP-Debian:/home/emilio/notepadqq# 
root@HP-Debian:/home/emilio/notepadqq# 
root@HP-Debian:/home/emilio/notepadqq# 
root@HP-Debian:/home/emilio/notepadqq# 
root@HP-Debian:/home/emilio/notepadqq# make
cd src/ui/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/emilio/notepadqq/src/ui/ui.pro PREFIX=/usr QMAKE_CXX=c++ 'QMAKE_CXXFLAGS= ' QMAKE_LFLAGS= 'LRELEASE=/usr/bin/qtchooser -run-tool=lrelease -qt=5' CONFIG+= -o Makefile ) && make -f Makefile 
Project MESSAGE: Release build
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_de.qm'...
    Generated 453 translation(s) (453 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_es.qm'...
    Generated 365 translation(s) (365 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_fr.qm'...
    Generated 345 translation(s) (345 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_hu.qm'...
    Generated 448 translation(s) (448 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_it.qm'...
    Generated 345 translation(s) (345 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_ja.qm'...
    Generated 344 translation(s) (344 finished and 0 unfinished)
    Ignored 1 untranslated source text(s)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_pl.qm'...
    Generated 348 translation(s) (348 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_pt.qm'...
    Generated 345 translation(s) (345 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_ru.qm'...
    Generated 328 translation(s) (326 finished and 2 unfinished)
    Ignored 17 untranslated source text(s)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_sl.qm'...
    Generated 345 translation(s) (345 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_sv.qm'...
    Generated 359 translation(s) (359 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_uk.qm'...
    Generated 453 translation(s) (453 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_zh.qm'...
    Generated 448 translation(s) (448 finished and 0 unfinished)
make[1]: se entra en el directorio '/home/emilio/notepadqq/src/ui'
(cd "/home/emilio/notepadqq/src/ui" && rm -rf "../../out/release/lib/../appdata/editor" && cd "../editor" && make DESTDIR="../../out/release/lib/../appdata/editor")
make[2]: se entra en el directorio '/home/emilio/notepadqq/src/editor'
mkdir -p "../../out/release/lib/../appdata/editor"
cp -r classes styles features app.js index.html init.js Languages.json "../../out/release/lib/../appdata/editor"/
mkdir -p "../../out/release/lib/../appdata/editor"/libs
cp -r libs/jquery "../../out/release/lib/../appdata/editor"/libs/jquery/
cp -r libs/MathJax "../../out/release/lib/../appdata/editor"/libs/MathJax/
cp -r libs/require.js "../../out/release/lib/../appdata/editor"/libs/require.js/
# Call CodeMirror makefile passing DESTDIR as absolute path, so we have no problems with cd-ing to libs
make -C libs -f Makefile-codemirror DESTDIR="/home/emilio/notepadqq/out/release/appdata/$(basename "../../out/release/lib/../appdata/editor")"/libs/codemirror
make[3]: se entra en el directorio '/home/emilio/notepadqq/src/editor/libs'
mkdir -p "/home/emilio/notepadqq/out/release/appdata/editor/libs/codemirror"
cd codemirror && cp -r addon keymap lib mode theme LICENSE "/home/emilio/notepadqq/out/release/appdata/editor/libs/codemirror"/
# Clean unnecessary files within "mode"
find "/home/emilio/notepadqq/out/release/appdata/editor/libs/codemirror"/mode/ -type f -name '*.html' -exec rm -f {} +
find "/home/emilio/notepadqq/out/release/appdata/editor/libs/codemirror"/mode/ -type f -name 'test.js' -exec rm -f {} +
cd "/home/emilio/notepadqq/out/release/appdata/editor/libs/codemirror"/mode/m4/ && rm -f *.txt *.sh *.in
make[3]: se sale del directorio '/home/emilio/notepadqq/src/editor/libs'
make[2]: se sale del directorio '/home/emilio/notepadqq/src/editor'
(cd "/home/emilio/notepadqq/src/ui" && rm -rf "../../out/release/lib/../appdata/extension_tools" && cd "../extension_tools" && make DESTDIR="../../out/release/lib/../appdata/extension_tools")
make[2]: se entra en el directorio '/home/emilio/notepadqq/src/extension_tools'
mkdir -p "../../out/release/lib/../appdata/extension_tools"
cp -r node_modules install.js pack.js package.json readmanifest.js "../../out/release/lib/../appdata/extension_tools"/
make[2]: se sale del directorio '/home/emilio/notepadqq/src/extension_tools'
(/usr/bin/qtchooser -run-tool=lrelease -qt=5 "/home/emilio/notepadqq/src/ui/ui.pro")
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_de.qm'...
    Generated 453 translation(s) (453 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_es.qm'...
    Generated 365 translation(s) (365 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_fr.qm'...
    Generated 345 translation(s) (345 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_hu.qm'...
    Generated 448 translation(s) (448 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_it.qm'...
    Generated 345 translation(s) (345 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_ja.qm'...
    Generated 344 translation(s) (344 finished and 0 unfinished)
    Ignored 1 untranslated source text(s)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_pl.qm'...
    Generated 348 translation(s) (348 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_pt.qm'...
    Generated 345 translation(s) (345 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_ru.qm'...
    Generated 328 translation(s) (326 finished and 2 unfinished)
    Ignored 17 untranslated source text(s)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_sl.qm'...
    Generated 345 translation(s) (345 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_sv.qm'...
    Generated 359 translation(s) (359 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_uk.qm'...
    Generated 453 translation(s) (453 finished and 0 unfinished)
Updating '/home/emilio/notepadqq/src/ui/../translations/notepadqq_zh.qm'...
    Generated 448 translation(s) (448 finished and 0 unfinished)
(cd "/home/emilio/notepadqq/src/ui" && mkdir -p "../../out/release/lib/../bin/" && cp -f "../../support_files/launch/notepadqq" "../../out/release/lib/../bin/" && chmod 755 "../../out/release/lib/../bin/notepadqq")
/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainwindow.ui -o ../../out/build_data/ui_mainwindow.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic frmabout.ui -o ../../out/build_data/ui_frmabout.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic frmpreferences.ui -o ../../out/build_data/ui_frmpreferences.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic frmencodingchooser.ui -o ../../out/build_data/ui_frmencodingchooser.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic frmindentationmode.ui -o ../../out/build_data/ui_frmindentationmode.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic Search/dlgsearching.ui -o ../../out/build_data/ui_dlgsearching.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic Search/frmsearchreplace.ui -o ../../out/build_data/ui_frmsearchreplace.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic frmlinenumberchooser.ui -o ../../out/build_data/ui_frmlinenumberchooser.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic Extensions/installextension.ui -o ../../out/build_data/ui_installextension.h
c++ -c -O2 -std=gnu++1y -Wall -W -Wold-style-cast -D_REENTRANT -fPIC -DQT_NO_URL_CAST_FROM_STRING -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_PRINTSUPPORT_LIB -DQT_WEBENGINEWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Ilibs/qtpromise/include -Ilibs/qtpromise/src -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebChannel -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebSockets -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I../../out/build_data -I../../out/build_data -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o ../../out/build_data/main.o main.cpp
c++ -c -O2 -std=gnu++1y -Wall -W -Wold-style-cast -D_REENTRANT -fPIC -DQT_NO_URL_CAST_FROM_STRING -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_PRINTSUPPORT_LIB -DQT_WEBENGINEWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Ilibs/qtpromise/include -Ilibs/qtpromise/src -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebChannel -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebSockets -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I../../out/build_data -I../../out/build_data -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o ../../out/build_data/mainwindow.o mainwindow.cpp
c++ -c -O2 -std=gnu++1y -Wall -W -Wold-style-cast -D_REENTRANT -fPIC -DQT_NO_URL_CAST_FROM_STRING -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_PRINTSUPPORT_LIB -DQT_WEBENGINEWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Ilibs/qtpromise/include -Ilibs/qtpromise/src -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebChannel -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebSockets -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I../../out/build_data -I../../out/build_data -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o ../../out/build_data/topeditorcontainer.o topeditorcontainer.cpp
topeditorcontainer.cpp: In instantiation of ‘TopEditorContainer::forEachEditorAsync(bool, std::function<void(int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>, std::function<void()>)>)::<lambda(const auto:1&, const auto:2&)>::<lambda(int, int)>::<lambda()> [with auto:1 = QtPromise::QPromiseResolve<void>; auto:2 = QtPromise::QPromiseReject<void>]’:
topeditorcontainer.cpp:225:21:   required from ‘struct TopEditorContainer::forEachEditorAsync(bool, std::function<void(int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>, std::function<void()>)>)::<lambda(const auto:1&, const auto:2&)>::<lambda(int, int)> [with auto:1 = QtPromise::QPromiseResolve<void>; auto:2 = QtPromise::QPromiseReject<void>]::<lambda()>’
topeditorcontainer.cpp:227:13:   required from ‘TopEditorContainer::forEachEditorAsync(bool, std::function<void(int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>, std::function<void()>)>)::<lambda(const auto:1&, const auto:2&)>::<lambda(int, int)> [with auto:1 = QtPromise::QPromiseResolve<void>; auto:2 = QtPromise::QPromiseReject<void>]’
topeditorcontainer.cpp:225:21:   required from ‘struct TopEditorContainer::forEachEditorAsync(bool, std::function<void(int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>, std::function<void()>)>)::<lambda(const auto:1&, const auto:2&)> [with auto:1 = QtPromise::QPromiseResolve<void>; auto:2 = QtPromise::QPromiseReject<void>]::<lambda(int, int)>’
topeditorcontainer.cpp:227:13:   required from ‘TopEditorContainer::forEachEditorAsync(bool, std::function<void(int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>, std::function<void()>)>)::<lambda(const auto:1&, const auto:2&)> [with auto:1 = QtPromise::QPromiseResolve<void>; auto:2 = QtPromise::QPromiseReject<void>]’
libs/qtpromise/include/../src/qtpromise/qpromise.inl:97:17:   required from ‘QtPromise::QPromiseBase<T>::QPromiseBase(F) [with F = TopEditorContainer::forEachEditorAsync(bool, std::function<void(int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>, std::function<void()>)>)::<lambda(const auto:1&, const auto:2&)>; typename std::enable_if<(QtPromisePrivate::ArgsOf<F>::count != 1), int>::type <anonymous> = 0; T = void]’
libs/qtpromise/include/../src/qtpromise/qpromise.h:103:73:   required from ‘QtPromise::QPromise<void>::QPromise(F&&) [with F = TopEditorContainer::forEachEditorAsync(bool, std::function<void(int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>, std::function<void()>)>)::<lambda(const auto:1&, const auto:2&)>]’
topeditorcontainer.cpp:250:6:   required from here
topeditorcontainer.cpp:219:53: error: cannot call member function ‘EditorTabWidget* TopEditorContainer::tabWidget(int)’ without object
                             iteration(i-1, tabWidget(i-1)->count() - 1);
                                            ~~~~~~~~~^~~~~
topeditorcontainer.cpp:224:54: error: cannot call member function ‘EditorTabWidget* TopEditorContainer::tabWidget(int)’ without object
                     EditorTabWidget *tabW = tabWidget(i);
                                             ~~~~~~~~~^~~
topeditorcontainer.cpp:225:29: error: no match for call to ‘(const std::function<void(int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>, std::function<void()>)>) (const int&, const int&, EditorTabWidget*&, EditorNS::Editor*, std::function<void()>, TopEditorContainer::forEachEditorAsync(bool, std::function<void(int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>, std::function<void()>)>)::<lambda(const auto:1&, const auto:2&)>::<lambda(int, int)>::<lambda()> [with auto:1 = QtPromise::QPromiseResolve<void>; auto:2 = QtPromise::QPromiseReject<void>]::<lambda()>)’
                     callback(i, j, tabW, tabW->editor(j), iteration(i, j-1), [resolve](){ resolve(); });
                     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libs/qtpromise/include/../src/qtpromise/qpromiseglobal.h:9:0,
                 from libs/qtpromise/include/../src/qtpromise/qpromiseerror.h:5,
                 from libs/qtpromise/include/../src/qtpromise/qpromise_p.h:5,
                 from libs/qtpromise/include/../src/qtpromise/qpromise.h:5,
                 from libs/qtpromise/include/QtPromise:9,
                 from include/EditorNS/editor.h:13,
                 from include/topeditorcontainer.h:4,
                 from topeditorcontainer.cpp:1:
/usr/include/c++/6/functional:2122:5: note: candidate: _Res std::function<_Res(_ArgTypes ...)>::operator()(_ArgTypes ...) const [with _Res = void; _ArgTypes = {int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>, std::function<void()>}]
     function<_Res(_ArgTypes...)>::
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6/functional:2122:5: note:   no known conversion for argument 6 from ‘TopEditorContainer::forEachEditorAsync(bool, std::function<void(int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>, std::function<void()>)>)::<lambda(const auto:1&, const auto:2&)>::<lambda(int, int)>::<lambda()> [with auto:1 = QtPromise::QPromiseResolve<void>; auto:2 = QtPromise::QPromiseReject<void>]::<lambda()>’ to ‘std::function<void()>’
topeditorcontainer.cpp: In instantiation of ‘TopEditorContainer::forEachEditorAsync(bool, std::function<void(int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>, std::function<void()>)>)::<lambda(const auto:1&, const auto:2&)> [with auto:1 = QtPromise::QPromiseResolve<void>; auto:2 = QtPromise::QPromiseReject<void>]’:
libs/qtpromise/include/../src/qtpromise/qpromise.inl:97:17:   required from ‘QtPromise::QPromiseBase<T>::QPromiseBase(F) [with F = TopEditorContainer::forEachEditorAsync(bool, std::function<void(int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>, std::function<void()>)>)::<lambda(const auto:1&, const auto:2&)>; typename std::enable_if<(QtPromisePrivate::ArgsOf<F>::count != 1), int>::type <anonymous> = 0; T = void]’
libs/qtpromise/include/../src/qtpromise/qpromise.h:103:73:   required from ‘QtPromise::QPromise<void>::QPromise(F&&) [with F = TopEditorContainer::forEachEditorAsync(bool, std::function<void(int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>, std::function<void()>)>)::<lambda(const auto:1&, const auto:2&)>]’
topeditorcontainer.cpp:250:6:   required from here
topeditorcontainer.cpp:229:28: error: cannot call member function ‘int QSplitter::count() const’ without object
             iteration(count() - 1, tabWidget(0)->count() - 1)();
                       ~~~~~^~
topeditorcontainer.cpp:229:45: error: cannot call member function ‘EditorTabWidget* TopEditorContainer::tabWidget(int)’ without object
             iteration(count() - 1, tabWidget(0)->count() - 1)();
                                    ~~~~~~~~~^~~
topeditorcontainer.cpp:246:13: error: conversion from ‘TopEditorContainer::forEachEditorAsync(bool, std::function<void(int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>, std::function<void()>)>)::<lambda(const auto:1&, const auto:2&)> [with auto:1 = QtPromise::QPromiseResolve<void>; auto:2 = QtPromise::QPromiseReject<void>]::<lambda(int, int)>’ to non-scalar type ‘std::function<std::function<void()>(int, int)>’ requested
             };
             ^
topeditorcontainer.cpp: In instantiation of ‘TopEditorContainer::forEachEditorConcurrent(std::function<void(int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>)>)::<lambda(const auto:3&, const auto:4&)> [with auto:3 = QtPromise::QPromiseResolve<void>; auto:4 = QtPromise::QPromiseReject<void>]’:
libs/qtpromise/include/../src/qtpromise/qpromise.inl:97:17:   required from ‘QtPromise::QPromiseBase<T>::QPromiseBase(F) [with F = TopEditorContainer::forEachEditorConcurrent(std::function<void(int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>)>)::<lambda(const auto:3&, const auto:4&)>; typename std::enable_if<(QtPromisePrivate::ArgsOf<F>::count != 1), int>::type <anonymous> = 0; T = void]’
libs/qtpromise/include/../src/qtpromise/qpromise.h:103:73:   required from ‘QtPromise::QPromise<void>::QPromise(F&&) [with F = TopEditorContainer::forEachEditorConcurrent(std::function<void(int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>)>)::<lambda(const auto:3&, const auto:4&)>]’
topeditorcontainer.cpp:280:6:   required from here
topeditorcontainer.cpp:259:34: error: cannot call member function ‘int QSplitter::count() const’ without object
         for (int i = 0; i < count(); i++) {
                             ~~~~~^~
topeditorcontainer.cpp:260:46: error: cannot call member function ‘EditorTabWidget* TopEditorContainer::tabWidget(int)’ without object
             EditorTabWidget *tabW = tabWidget(i);
                                     ~~~~~~~~~^~~
topeditorcontainer.cpp:272:37: error: cannot call member function ‘EditorTabWidget* TopEditorContainer::tabWidget(int)’ without object
             callback(i, j, tabWidget(i), tabWidget(i)->editor(j), [cnt, resolve](){
                            ~~~~~~~~~^~~
topeditorcontainer.cpp:272:51: error: cannot call member function ‘EditorTabWidget* TopEditorContainer::tabWidget(int)’ without object
             callback(i, j, tabWidget(i), tabWidget(i)->editor(j), [cnt, resolve](){
                                          ~~~~~~~~~^~~
In file included from libs/qtpromise/include/../src/qtpromise/qpromiseglobal.h:9:0,
                 from libs/qtpromise/include/../src/qtpromise/qpromiseerror.h:5,
                 from libs/qtpromise/include/../src/qtpromise/qpromise_p.h:5,
                 from libs/qtpromise/include/../src/qtpromise/qpromise.h:5,
                 from libs/qtpromise/include/QtPromise:9,
                 from include/EditorNS/editor.h:13,
                 from include/topeditorcontainer.h:4,
                 from topeditorcontainer.cpp:1:
/usr/include/c++/6/functional:2106:7: error: ‘std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = TopEditorContainer::forEachEditorAsync(bool, std::function<void(int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>, std::function<void()>)>)::<lambda(const auto:1&, const auto:2&)> [with auto:1 = QtPromise::QPromiseResolve<void>; auto:2 = QtPromise::QPromiseReject<void>]::<lambda(int, int)>; <template-parameter-2-2> = void; <template-parameter-2-3> = void; _Res = std::function<void()>; _ArgTypes = {int, int}]’, declared using local type ‘TopEditorContainer::forEachEditorAsync(bool, std::function<void(int, int, EditorTabWidget*, EditorNS::Editor*, std::function<void()>, std::function<void()>)>)::<lambda(const auto:1&, const auto:2&)> [with auto:1 = QtPromise::QPromiseResolve<void>; auto:2 = QtPromise::QPromiseReject<void>]::<lambda(int, int)>’, is used but never defined [-fpermissive]
       function<_Res(_ArgTypes...)>::
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:1178: fallo en las instrucciones para el objetivo '../../out/build_data/topeditorcontainer.o'
make[1]: *** [../../out/build_data/topeditorcontainer.o] Error 1
make[1]: se sale del directorio '/home/emilio/notepadqq/src/ui'
Makefile:43: fallo en las instrucciones para el objetivo 'sub-src-ui-make_first'
make: *** [sub-src-ui-make_first] Error 2

**Please tell us about your environment:**
Linux version 4.9.0-6-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07)

**Comment by JuBan1** [comment]
This is a compilation error [that happens on older GCC versions](https://stackoverflow.com/questions/32097759/calling-this-member-function-from-generic-lambda-clang-vs-gcc) like yours. 

I have fixed the issues in your error log, but there could be more. I don't have a GCC 6 compiler so its difficult for me to fix this.

Are you using Debian? What version? Maybe I can install it as a virtual machine and test the compilation myself.

**Comment by kraamis** [comment]
I confirm this bug. I use Debian Stable and Debian Testing. On both version of Debian, i can't compile notepadqq, but one month ago all was well. GCC version - 6.3.

**Comment by kraamis** [comment]
for GCC 7.3 this bug also exists

**Comment by JuBan1** [comment]
Fixed by f004282. Took a while because I ended up setting up a Debian VM for testing.

Most of the issues arose from GCC-6 having a few bugs in the implementation of a C++ feature. Compiles smoothly for me now. Haven't tested GCC-7 but if 6 works then 7 is all but guaranteed to work too.

**Comment by kraamis** [comment]
Unfortunately the bug persists. What additional information should I provide?

**Comment by JuBan1** [comment]
Yea, you've got a different error:

> Project ERROR: Unknown module(s) in QT: webenginewidgets webchannel websockets

You need to install some extra packages. I think this should be enough `apt-get install qtwebengine5-dev`.

**Comment by kraamis** [comment]
Unfortunately, it did not help.

kraamis@debian [~]$ sudo apt-get install qtwebengine5-dev
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Будут установлены следующие дополнительные пакеты:
  libqt5positioning5-plugins libqt5webchannel5-dev libqt5webengine-data libqt5webengine5 libqt5webenginecore5 libqt5webenginewidgets5 libre2-4 qtpositioning5-dev qtwebengine5-doc
НОВЫЕ пакеты, которые будут установлены:
  libqt5positioning5-plugins libqt5webchannel5-dev libqt5webengine-data libqt5webengine5 libqt5webenginecore5 libqt5webenginewidgets5 libre2-4 qtpositioning5-dev qtwebengine5-dev qtwebengine5-doc
Обновлено 0 пакетов, установлено 10 новых пакетов, для удаления отмечено 0 пакетов, и 0 пакетов не обновлено.
Необходимо скачать 36,4 MB архивов.
После данной операции, объём занятого дискового пространства возрастёт на 134 MB.
Хотите продолжить? [Д/н] y
Пол:1 http://ftp.ru.debian.org/debian testing/main amd64 libqt5positioning5-plugins amd64 5.10.1+dfsg-3 [57,3 kB]
Пол:2 http://ftp.ru.debian.org/debian testing/main amd64 libqt5webchannel5-dev amd64 5.10.1-2 [10,3 kB]
Пол:3 http://ftp.ru.debian.org/debian testing/main amd64 libqt5webengine-data all 5.10.1+dfsg-4 [4 996 kB]
Пол:4 http://ftp.ru.debian.org/debian testing/main amd64 libre2-4 amd64 20180301+dfsg-1 [187 kB]                                                                                                                                        
Пол:5 http://ftp.ru.debian.org/debian testing/main amd64 libqt5webenginecore5 amd64 5.10.1+dfsg-4 [28,3 MB]                                                                                                                             
Пол:6 http://ftp.ru.debian.org/debian testing/main amd64 libqt5webengine5 amd64 5.10.1+dfsg-4 [174 kB]                                                                                                                                  
Пол:7 http://ftp.ru.debian.org/debian testing/main amd64 libqt5webenginewidgets5 amd64 5.10.1+dfsg-4 [136 kB]                                                                                                                           
Пол:8 http://ftp.ru.debian.org/debian testing/main amd64 qtpositioning5-dev amd64 5.10.1+dfsg-3 [18,5 kB]                                                                                                                               
Пол:9 http://ftp.ru.debian.org/debian testing/main amd64 qtwebengine5-dev amd64 5.10.1+dfsg-4 [91,1 kB]                                                                                                                                 
Пол:10 http://ftp.ru.debian.org/debian testing/main amd64 qtwebengine5-doc all 5.10.1+dfsg-4 [2 366 kB]                                                                                                                                 
Получено 36,4 MB за 2мин 47с (217 kB/s)                                                                                                                                                                                                 
Выбор ранее не выбранного пакета libqt5positioning5-plugins:amd64.
(Чтение базы данных … на данный момент установлено 193115 файлов и каталогов.)
Подготовка к распаковке …/0-libqt5positioning5-plugins_5.10.1+dfsg-3_amd64.deb …
Распаковывается libqt5positioning5-plugins:amd64 (5.10.1+dfsg-3) …
Выбор ранее не выбранного пакета libqt5webchannel5-dev:amd64.
Подготовка к распаковке …/1-libqt5webchannel5-dev_5.10.1-2_amd64.deb …
Распаковывается libqt5webchannel5-dev:amd64 (5.10.1-2) …
Выбор ранее не выбранного пакета libqt5webengine-data.
Подготовка к распаковке …/2-libqt5webengine-data_5.10.1+dfsg-4_all.deb …
Распаковывается libqt5webengine-data (5.10.1+dfsg-4) …
Выбор ранее не выбранного пакета libre2-4:amd64.
Подготовка к распаковке …/3-libre2-4_20180301+dfsg-1_amd64.deb …
Распаковывается libre2-4:amd64 (20180301+dfsg-1) …
Выбор ранее не выбранного пакета libqt5webenginecore5:amd64.
Подготовка к распаковке …/4-libqt5webenginecore5_5.10.1+dfsg-4_amd64.deb …
Распаковывается libqt5webenginecore5:amd64 (5.10.1+dfsg-4) …
Выбор ранее не выбранного пакета libqt5webengine5:amd64.
Подготовка к распаковке …/5-libqt5webengine5_5.10.1+dfsg-4_amd64.deb …
Распаковывается libqt5webengine5:amd64 (5.10.1+dfsg-4) …
Выбор ранее не выбранного пакета libqt5webenginewidgets5:amd64.
Подготовка к распаковке …/6-libqt5webenginewidgets5_5.10.1+dfsg-4_amd64.deb …
Распаковывается libqt5webenginewidgets5:amd64 (5.10.1+dfsg-4) …
Выбор ранее не выбранного пакета qtpositioning5-dev:amd64.
Подготовка к распаковке …/7-qtpositioning5-dev_5.10.1+dfsg-3_amd64.deb …
Распаковывается qtpositioning5-dev:amd64 (5.10.1+dfsg-3) …
Выбор ранее не выбранного пакета qtwebengine5-dev:amd64.
Подготовка к распаковке …/8-qtwebengine5-dev_5.10.1+dfsg-4_amd64.deb …
Распаковывается qtwebengine5-dev:amd64 (5.10.1+dfsg-4) …
Выбор ранее не выбранного пакета qtwebengine5-doc.
Подготовка к распаковке …/9-qtwebengine5-doc_5.10.1+dfsg-4_all.deb …
Распаковывается qtwebengine5-doc (5.10.1+dfsg-4) …
Настраивается пакет qtwebengine5-doc (5.10.1+dfsg-4) …
Настраивается пакет libqt5webengine-data (5.10.1+dfsg-4) …
Настраивается пакет libre2-4:amd64 (20180301+dfsg-1) …
Обрабатываются триггеры для libc-bin (2.27-3) …
Настраивается пакет libqt5webchannel5-dev:amd64 (5.10.1-2) …
Настраивается пакет libqt5webenginecore5:amd64 (5.10.1+dfsg-4) …
Настраивается пакет libqt5positioning5-plugins:amd64 (5.10.1+dfsg-3) …
Настраивается пакет qtpositioning5-dev:amd64 (5.10.1+dfsg-3) …
Настраивается пакет libqt5webenginewidgets5:amd64 (5.10.1+dfsg-4) …
Настраивается пакет libqt5webengine5:amd64 (5.10.1+dfsg-4) …
Настраивается пакет qtwebengine5-dev:amd64 (5.10.1+dfsg-4) …
Обрабатываются триггеры для libc-bin (2.27-3) …

kraamis@debian [~]$ ls -l
итого 592
drwxr-xr-x 12 kraamis kraamis   4096 июн 25 21:22  notepadqq
-rw-r--r--  1 kraamis kraamis 281451 июн 25 21:19  PackageList
drwxr-xr-x 10 kraamis kraamis   4096 июн 24 21:18  pycharm-community-2018.1.4
-rwxr-xr-x  1 kraamis kraamis 278926 июн 24 22:43  waterfall.jpg
-rw-r--r--  1 kraamis kraamis      0 июн 24 21:38  wget-log
-rw-r--r--  1 kraamis kraamis      0 июн 25 20:09  wget-log.1
drwxr-xr-x  2 kraamis kraamis   4096 июн 24 18:14  Видео
drwxr-xr-x  2 kraamis kraamis   4096 июн 24 18:14  Документы
drwxr-xr-x  2 kraamis kraamis   4096 июн 24 21:14  Загрузки
drwxr-xr-x  2 kraamis kraamis   4096 июн 24 18:14  Изображения
drwxr-xr-x  2 kraamis kraamis   4096 июн 24 18:14  Музыка
drwxr-xr-x  2 kraamis kraamis   4096 июн 24 18:14  Общедоступные
drwxr-xr-x  2 kraamis kraamis   4096 июн 24 18:14 'Рабочий стол'
drwxr-xr-x  2 kraamis kraamis   4096 июн 24 18:14  Шаблоны

kraamis@debian [~]$ rm -rf notepadqq

kraamis@debian [~]$ git clone https://github.com/notepadqq/notepadqq.git
Клонирование в «notepadqq»…
remote: Counting objects: 14767, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 14767 (delta 16), reused 30 (delta 14), pack-reused 14724
Получение объектов: 100% (14767/14767), 8.84 MiB | 1.01 MiB/s, готово.
Определение изменений: 100% (8482/8482), готово.

kraamis@debian [~]$ cd notepadqq

kraamis@debian [notepadqq]$ ./configure --prefix /usr --qmake /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
checking for QT5 qmake... /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
checking for lrelease... /usr/bin/qtchooser -run-tool=lrelease -qt=5
checking for c++... /usr/bin/c++
checking whether c++ compiler builds test program... ok
checking whether c++ compiler supports -std=c++0x... ok
checking whether compiled test program works... ok
checking for make... /usr/bin/make
checking for pkg-config... not found!
generate Makefile... Info: creating stash file /home/kraamis/notepadqq/.qmake.stash
done

kraamis@debian [notepadqq]$ make
cd src/ui/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile /home/kraamis/notepadqq/src/ui/ui.pro PREFIX=/usr QMAKE_CXX=c++ 'QMAKE_CXXFLAGS= ' QMAKE_LFLAGS= 'LRELEASE=/usr/bin/qtchooser -run-tool=lrelease -qt=5' CONFIG+= ) && make -f Makefile 
Project MESSAGE: Release build
WARNING: Project ERROR: Unknown module(s) in QT: websockets
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_de.qm'...
    Создано 453 перевода (453 завершённых и 0 незавершённых)
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_es.qm'...
    Создано 365 переводов (365 завершённых и 0 незавершённых)
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_fr.qm'...
    Создано 345 переводов (345 завершённых и 0 незавершённых)
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_hu.qm'...
    Создано 448 переводов (448 завершённых и 0 незавершённых)
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_it.qm'...
    Создано 345 переводов (345 завершённых и 0 незавершённых)
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_ja.qm'...
    Создано 344 перевода (344 завершённых и 0 незавершённых)
    Пропущен 1 непереведённый исходный текст
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_pl.qm'...
    Создано 348 переводов (348 завершённых и 0 незавершённых)
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_pt.qm'...
    Создано 345 переводов (345 завершённых и 0 незавершённых)
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_ru.qm'...
    Создано 328 переводов (326 завершённых и 2 незавершённых)
    Пропущено 17 непереведённых исходных текстов
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_sl.qm'...
    Создано 345 переводов (345 завершённых и 0 незавершённых)
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_sv.qm'...
    Создано 359 переводов (359 завершённых и 0 незавершённых)
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_uk.qm'...
    Создано 453 перевода (453 завершённых и 0 незавершённых)
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_zh.qm'...
    Создано 448 переводов (448 завершённых и 0 незавершённых)
Project ERROR: Unknown module(s) in QT: websockets
Makefile:45: ошибка выполнения рецепта для цели «sub-src-ui-make_first»
make: *** [sub-src-ui-make_first] Ошибка 3

kraamis@debian [notepadqq]$ sudo make install
cd src/ui/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile /home/kraamis/notepadqq/src/ui/ui.pro PREFIX=/usr QMAKE_CXX=c++ 'QMAKE_CXXFLAGS= ' QMAKE_LFLAGS= 'LRELEASE=/usr/bin/qtchooser -run-tool=lrelease -qt=5' CONFIG+= ) && make -f Makefile install
Project MESSAGE: Release build
WARNING: Project ERROR: Unknown module(s) in QT: websockets
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_de.qm'...
    Создано 453 перевода (453 завершённых и 0 незавершённых)
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_es.qm'...
    Создано 365 переводов (365 завершённых и 0 незавершённых)
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_fr.qm'...
    Создано 345 переводов (345 завершённых и 0 незавершённых)
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_hu.qm'...
    Создано 448 переводов (448 завершённых и 0 незавершённых)
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_it.qm'...
    Создано 345 переводов (345 завершённых и 0 незавершённых)
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_ja.qm'...
    Создано 344 перевода (344 завершённых и 0 незавершённых)
    Пропущен 1 непереведённый исходный текст
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_pl.qm'...
    Создано 348 переводов (348 завершённых и 0 незавершённых)
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_pt.qm'...
    Создано 345 переводов (345 завершённых и 0 незавершённых)
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_ru.qm'...
    Создано 328 переводов (326 завершённых и 2 незавершённых)
    Пропущено 17 непереведённых исходных текстов
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_sl.qm'...
    Создано 345 переводов (345 завершённых и 0 незавершённых)
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_sv.qm'...
    Создано 359 переводов (359 завершённых и 0 незавершённых)
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_uk.qm'...
    Создано 453 перевода (453 завершённых и 0 незавершённых)
Updating '/home/kraamis/notepadqq/src/ui/../translations/notepadqq_zh.qm'...
    Создано 448 переводов (448 завершённых и 0 незавершённых)
Project ERROR: Unknown module(s) in QT: websockets
Makefile:57: ошибка выполнения рецепта для цели «sub-src-ui-install_subtargets»
make: *** [sub-src-ui-install_subtargets] Ошибка 3

**Comment by JuBan1** [comment]
Yeh, sorry. I edited my last comment a minute after posting but that was probably too late :)

You need `libqt5websockets5-dev` too.

For reference, the dependencies are [listed here too](https://github.com/notepadqq/notepadqq#build-it-yourself).

**Comment by kraamis** [comment]
Excellent! Working!

Thank you very much for your help and for the excellent program!
