### ISSUE TITLE
The cursor line is invisible (does not blink)

### ISSUE THREAD

**Issue by tux871** [notepadqq/notepadqq#887]
Manjaro Cinnamon 5.2.8-1

The problem appears on notepadqq 1.4.8-2 (installed from the community repository) and on notepadqq-legacy 1.3.6-1 (installed from aur).

Qt version 5.13.0

**Comment by tux871** [comment]
The problem was resolved when I set the QT_SCALE_FACTOR environment variable to 1.0 (it was 1.2). Looks like a notepadqq bug? Other qt5 applications work correctly with QT_SCALE_FACTOR = 1.2.

**Comment by danieleds** [comment]
This should be fixed in master.
Closing for now, feel free to reopen in case you want to add more information :)

**Comment by OlegZharkov** [comment]
@tux871 
I have the same issue
Where did you specify this parameter?

**Comment by OlegZharkov** [comment]
Changed QT_SCALE_FACTOR to 1.0, didn't solve an issue for me. Are there any other ideas?

**Comment by CRASH-Tech** [comment]
Same issue. 
Works only if QT_SCALE_FACTOR=1.4, but it make window too big on my 4k screen.

**Comment by fodi** [comment]
Unfortunately I can second this issue. I'm running 64-bit KDE Neon 5.19 using NVIDIA drivers, KDE Plasma 5.19.0, KDE Frameworks 5.70.0, Qt 5.14.2. Global scale setting is at 125%.

**Comment by velemas** [comment]
I have the same issue with Plasma 5.20 (qt 5.15.1) on Arch.

**Comment by hasmar04** [comment]
I have this issue too on Manjaro Stable 20.2 with the version from the community repository. Hopefully there is  fix because this is really annoying and makes it impossible to use.

**Comment by panoweb** [comment]
Try changing the value in Notepadqq settings->preferences->appearance->override font size , in case the program didnt do it by itself.

**Comment by hasmar04** [comment]
> Try changing the value in Notepadqq settings->preferences->appearance->override font size , in case the program didnt do it by itself.

Just tried this and nothing changed.

**Comment by panoweb** [comment]
One reason this can be, is because of scaling settings. So, try them all either in or out of notepadqq.

**Comment by shakeelansari63** [comment]
The issue still exist. I am on Manjaro 20.2 Stable using notepadqq from the repo. 
The issue is quite annoying as the you can't see where the cursor is at.

Shouldn't this issue be re-opened?

**Comment by strainer** [comment]
I have no cursor on my up-to-date Manjaro install. I tried some alternative font and screen scaling values without success. Understood this may be a gtk bug, however it doesn't seem to be affecting any other editors or apps on my system.

**Comment by froshyfrosh** [comment]
On a freshly installed OpenSuse (KDE) I also cannot see the cursor. But when I change the zoom level in Notepadqq with Ctrl+MouseWheel the cursor gets visible for some and disappears again for other scale factors. This only seems to work with 'Settings -> Appearance ->  Override Font Size' enabled (14 in my case), otherwise the cursor never gets visible.

'Global Scale' is 125% (System settings -> Display and Monitor -> Display Configuration) and I am using proprietary nVidia drivers.

**Comment by LeggoMahEggo** [comment]
I have the same scaling issue on my Manjaro laptop; tried chuyaqifei's solution, but unfortunately it didn't work for me. Here are my device specs:

**System:**    Kernel: 5.10.83-1-MANJARO x86_64 bits: 64 compiler: gcc v: 11.1.0 Desktop: KDE Plasma 5.23.4 tk: Qt 5.15.2
           wm: kwin_x11 vt: 1 dm: SDDM Distro: Manjaro Linux base: Arch Linux
**Machine:**   Type: Laptop System: ASUSTeK product: VivoBook_ASUSLaptop X415JA_X415JA v: 1.0 serial: <superuser required>
           Mobo: ASUSTeK model: X415JA v: 1.0 serial: <superuser required> UEFI: American Megatrends v: X415JA.300
           date: 08/19/2020
**Battery:**   ID-1: BAT0 charge: 19.1 Wh (60.6%) condition: 31.5/37.1 Wh (85.0%) volts: 7.8 min: 7.8 model: ASUSTeK ASUS Battery
           type: Li-ion serial: N/A status: Charging cycles: 104
**Memory:**    RAM: total: 7.52 GiB used: 4.99 GiB (66.4%)
           RAM Report: permissions: Unable to run dmidecode. Root privileges required.
**CPU:**       Info: Dual Core model: Intel Core i3-1005G1 bits: 64 type: MT MCP arch: Ice Lake rev: 5 cache: L1: 160 KiB
           L2: 1024 KiB L3: 4 MiB bogomips: 9524
           Speed: 1142 MHz min/max: 400/3400 MHz Core speeds (MHz): 1: 1194 2: 1201 3: 1227 4: 1197
           Flags: 3dnowprefetch abm acpi adx aes aperfmperf apic arat arch_capabilities arch_perfmon art avx avx2
           avx512_bitalg avx512_vbmi2 avx512_vnni avx512_vpopcntdq avx512bw avx512cd avx512dq avx512f avx512ifma avx512vbmi
           avx512vl bmi1 bmi2 bts clflush clflushopt cmov constant_tsc cpuid cpuid_fault cx16 cx8 de ds_cpl dtes64 dtherm dts
           epb ept ept_ad erms est f16c flexpriority flush_l1d fma fpu fsgsbase fsrm fxsr gfni ht hwp hwp_act_window hwp_epp
           hwp_notify hwp_pkg_req ibpb ibrs ibrs_enhanced ida intel_pt invpcid invpcid_single lahf_lm lm mca mce md_clear mmx
           monitor movbe msr mtrr nonstop_tsc nopl nx ospke pae pat pbe pcid pclmulqdq pdcm pdpe1gb pebs pge pku pln pni
           popcnt pse pse36 pts rdpid rdrand rdseed rdtscp rep_good sdbg sep sha_ni smap smep split_lock_detect ss ssbd sse
           sse2 sse4_1 sse4_2 ssse3 stibp syscall tm tm2 tpr_shadow tsc tsc_adjust tsc_deadline_timer tsc_known_freq umip vaes
           vme vmx vnmi vpclmulqdq vpid x2apic xgetbv1 xsave xsavec xsaveopt xsaves xtopology xtpr
**Graphics:**  Device-1: Intel Iris Plus Graphics G1 vendor: ASUSTeK driver: i915 v: kernel bus-ID: 00:02.0 chip-ID: 8086:8a56
           class-ID: 0300
           Device-2: IMC Networks USB2.0 VGA UVC WebCam type: USB driver: uvcvideo bus-ID: 1-5:5 chip-ID: 13d3:5a11
           class-ID: 0e02
           Display: x11 server: X.Org 1.21.1.1 compositor: kwin_x11 driver: loaded: modesetting alternate: fbdev,vesa
           resolution: 1920x1200~60Hz s-dpi: 96
           OpenGL: renderer: Mesa Intel UHD Graphics (ICL GT1) v: 4.6 Mesa 21.2.5 direct render: Yes
**Audio:**     Device-1: Intel Ice Lake-LP Smart Sound Audio vendor: ASUSTeK driver: snd_hda_intel v: kernel bus-ID: 00:1f.3
           chip-ID: 8086:34c8 class-ID: 0403
           Sound Server-1: ALSA v: k5.10.83-1-MANJARO running: yes
           Sound Server-2: JACK v: 1.9.19 running: no
           Sound Server-3: PulseAudio v: 15.0 running: yes
           Sound Server-4: PipeWire v: 0.3.40 running: yes
**Network:**   Device-1: Intel Ice Lake-LP PCH CNVi WiFi driver: iwlwifi v: kernel bus-ID: 00:14.3 chip-ID: 8086:34f0
           class-ID: 0280
           IF: wlo1 state: up mac: <filter>
           IP v4: <filter> type: dynamic noprefixroute scope: global broadcast: <filter>
           IP v6: <filter> type: noprefixroute scope: link
           WAN IP: <filter>
**Bluetooth:** Device-1: Intel Bluetooth 9460/9560 Jefferson Peak (JfP) type: USB driver: btusb v: 0.8 bus-ID: 1-10:6
           chip-ID: 8087:0aaa class-ID: e001
           Report: rfkill ID: hci0 rfk-id: 3 state: down bt-service: enabled,running rfk-block: hardware: no software: yes
           address: see --recommends
**Logical:**   Message: No logical block device data found.
**RAID:**      Hardware-1: Intel 82801 Mobile SATA Controller [RAID mode] driver: ahci v: 3.0 port: 3060 bus-ID: 00:17.0
           chip-ID: 8086:282a rev: N/A class-ID: 0104
**Drives:**    Local Storage: total: 238.47 GiB used: 156.2 GiB (65.5%)
           ID-1: /dev/nvme0n1 vendor: Western Digital model: PC SN530 SDBPNPZ-256G-1002 size: 238.47 GiB speed: 31.6 Gb/s
           lanes: 4 type: SSD serial: <filter> rev: 21106000 temp: 35.9 C scheme: GPT
           Message: No optical or floppy data found.
**Partition:** ID-1: / size: 233.43 GiB used: 156.2 GiB (66.9%) fs: ext4 dev: /dev/nvme0n1p2 label: N/A
           uuid: 6a6dea90-8fad-4730-9bac-87d4b3c118e8
           ID-2: /boot/efi size: 299.4 MiB used: 312 KiB (0.1%) fs: vfat dev: /dev/nvme0n1p1 label: N/A uuid: 669B-77F5
**Swap:**      Alert: No swap data was found.
**Unmounted:** Message: No unmounted partitions found.
**USB:**       Hub-1: 1-0:1 info: Hi-speed hub with single TT ports: 12 rev: 2.0 speed: 480 Mb/s chip-ID: 1d6b:0002 class-ID: 0900
           Device-1: 1-1:2 info: Logitech M105 Optical Mouse type: Mouse driver: hid-generic,usbhid interfaces: 1 rev: 2.0
           speed: 1.5 Mb/s power: 100mA chip-ID: 046d:c077 class-ID: 0301
           Device-2: 1-2:3 info: Logitech Keyboard K120 type: Keyboard,HID driver: hid-generic,usbhid interfaces: 2 rev: 1.1
           speed: 1.5 Mb/s power: 90mA chip-ID: 046d:c31c class-ID: 0300
           Device-3: 1-4:4 info: Realtek RTS5129 Card Reader Controller type: <vendor specific>
           driver: rtsx_usb,rtsx_usb_ms,rtsx_usb_sdmmc interfaces: 1 rev: 2.0 speed: 480 Mb/s power: 500mA chip-ID: 0bda:0129
           class-ID: ff00 serial: <filter>
           Device-4: 1-5:5 info: IMC Networks USB2.0 VGA UVC WebCam type: Video driver: uvcvideo interfaces: 2 rev: 2.0
           speed: 480 Mb/s power: 500mA chip-ID: 13d3:5a11 class-ID: 0e02
           Device-5: 1-10:6 info: Intel Bluetooth 9460/9560 Jefferson Peak (JfP) type: Bluetooth driver: btusb interfaces: 2
           rev: 2.0 speed: 12 Mb/s power: 100mA chip-ID: 8087:0aaa class-ID: e001
           Hub-2: 2-0:1 info: Super-speed hub ports: 6 rev: 3.1 speed: 10 Gb/s chip-ID: 1d6b:0003 class-ID: 0900
**Sensors:**   System Temperatures: cpu: 57.0 C mobo: N/A
           Fan Speeds (RPM): cpu: 2900
**Info:**      Processes: 267 Uptime: 3m wakeups: 1 Init: systemd v: 249 Compilers: gcc: 11.1.0 clang: 13.0.0 Packages:
           pacman: 1592 Shell: Bash v: 5.1.12 running-in: konsole inxi: 3.3.09

**Comment by joickle** [comment]
This is still an issue in mid 2022, and it's isolated to this app.
